server:
  address: 0.0.0.0
  port: 4000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://{KEYCLOAKHOST}/realms/{REALMID}/protocol/openid-connect/certs

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR